# Generated by Django 4.2.6 on 2023-12-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0002_alter_modelprof_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprof',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.proffessia', verbose_name='Профессия'),
        ),
    ]
